# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1464dfdc3776500bdb0e37846981abddc30d98f49bbf38de937537a160fc7bc4f477b050ca3b5165b11ad6cf07248cf0173a696a92b970b695d7490c4699dca6

test:
  secret_key_base: f4d04fe7203d6ecc7b540038630d9008a1e693ee38b1d637edc6cde1234fc64e6c39e0f6ee5113c502f54d907a8b68096277cbf531e0bc68b9dccbc1a212f4da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
